### ISSUE TITLE
twitter bot

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#106]
I wrote a little R script [code/twitter_bot.R] that takes the data and generates some text, and 4 plots, and then posts it to a new twitter account (@ddhypothesis) that I made just for this. I got a dev account with twitter, and set-up the tokens for access. Locally, everything works fine. 

Q: Can you help me set up a chron job scheduler for this on the server* to run the script 1x/day? (*is it allowed?) 

Given the app is always loaded, I thought this might be a fun way to drive some interest. 

p.s. I'm still working in the enhance pathways branch, so pushed changes there. Also, I .gitignored the R file where I save the tokens. This is supposed to be loaded into the environment, so will need to do that for it to have access.

**Comment by johnbradley** [comment]
In OpenShift there is a CronJob that can will periodically run a job. 
Good to hear you already figured out the .gitignore bit. 
We can store the tokens as a secret in OpenShift and let OpenShift pretend it's a file.
Unfortunately our OpenShift console doesn't seem to have UI for managing CronJobs, so I will need to create it on the command line.
If there are different requirements we may need to build another image or add them to the requirements for our app.
I don't see the code for twitter_bot.R in the enhance pathways branch.

Do you want to try this out in OpenShift from the enhance pathways branch?

**Comment by matthewhirschey** [comment]
Perhaps it'd help if I pushed, after committing changes. 🤦‍♂️
It's there now. 

Great to hear that OpenShift will run it, and if you can whip up something easy from the command line for 1x/day, that'd be great. The script doesn't load the data (assumes that the data is already loaded; same assumption for the functions). The only extra package it requires is `rtweet`

The script is also assumed to run from start to finish. You'll see that I needed to create temp files to store the images before posting them, so we might also need to consider which directories can be written to in order to store these files. 

Otherwise, pretty simple stuff.

**Comment by johnbradley** [comment]
@matthewhirschey 
Could you create a `Generic Secret` in OpenShift with the contents of token.R? 

Steps
- Go to https://manage.cloud.duke.edu/console/project/depmap/create-secret
- Select "Generic Secret" in the `Secret Type`.
- For Secret Name type "twitter-bot-token"
- For Key type "token.R"
- For Value browser for your file or paste the contents in the box.
- Click Create.

I can then Setup a CronJob that will pull this in as code/token.R.

Thanks.

**Comment by matthewhirschey** [comment]
Done. 
As you can see, the R script calls a function from `rtweet` that creates the token, and stores it in the environment. I don't call `library()` because this never runs alone (it's run from within the other R script).

**Comment by johnbradley** [comment]
Running `twitter_bot.R` fails with `object 'surprise_genes' not found`
It looks like twitter_bot.R assumes `surprise_genes`, `gene_summary`, etc are already loaded in the R environment.
Do we need to add some `readRDS` calls or is there some other method to setup the R environment?

**Comment by matthewhirschey** [comment]
Yes, that is the assumption. If this is going to be run as a stand alone script (i.e not in the environment of the app), then I will add some `readRDS` and `source` calls.

**Comment by johnbradley** [comment]
@matthewhirschey Looks like you got the `readRDS` and `source` calls added. I think I have the CronJob ready to go.
Are you good with me setting it up to run at 12 to see if it works?

**Comment by matthewhirschey** [comment]
I gave a 👍, but I'll be more explicit: yes, OK to test anytime. Yesterday, I 'spammed' the one follower I had while developing it LOL. But really not that big of a deal

**Comment by johnbradley** [comment]
I finally got everything sorted out. There should be two new tweets. The one from around 12:40 is from the cron job.
There was an issue with `create_token` failing when trying to write `.rtweet_token.rds`. I used the set_renv flag = FALSE and passed the token directly to `post_tweet`.

@matthewhirschey What is the twitter handle we are posting to?

**Comment by matthewhirschey** [comment]
@ddhypothesis...naturally. 

https://twitter.com/ddhypothesis

*both new tweets are live!

**Comment by matthewhirschey** [comment]
Where is the cron job code? I'm curious to take a look.

**Comment by johnbradley** [comment]
I pushed the cron job template to the `enhance_pathways`.
https://github.com/matthewhirschey/ddh/blob/enhance_pathways/openshift/TwitterCronJob.yaml

**Comment by johnbradley** [comment]
The `schedule ` line value `"0 8 * * *"` specifies 8 AM: https://crontab.guru/every-day-8am

**Comment by johnbradley** [comment]
The version I deployed is slightly different from what I pushed to github. The current deployed version uses an image built from the `enhance_pathways` branch and will tweet around 12:40 each day. The version pushed to github should be good for when the `enhanced_pathways` branch is merged.
