### ISSUE TITLE
Look for causaleffect dependency

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#13]
https://github.com/hirscheylab/ddh/blob/5213ad2b48bef9f2d97e49df7c3e5fd33ab324ff/Dockerfile.shiny#L14

**Comment by dleehr** [comment]
This is installed in the Dockerfile.shiny but it's not clear why we need it.

**Comment by matthewhirschey** [comment]
This is an R package (https://cran.r-project.org/web/packages/causaleffect/index.html); is it a hold-over from some of the template in the Rocker container? I don't explicitly call it in any of my code.

**Comment by dleehr** [comment]
Yeah it was a leftover from the openshift shiny template I found:

https://github.com/CSCfi/shiny-openshift/blob/4a5f7a2af05028370b2672f3266fe1e59b9fa241/Dockerfile#L12-L29

So it can be removed

**Comment by dleehr** [comment]
Yeah it was a leftover from the openshift shiny template I found: https://github.com/CSCfi/shiny-openshift/blob/master/Dockerfile#L29. 

I don't think we're using [shinyWidgets](https://github.com/dreamRs/shinyWidgets) either

**Comment by matthewhirschey** [comment]
@dleehr Correct, not using shinyWidgets

**Comment by matthewhirschey** [comment]
Although perhaps we should... "This package provide some custom widgets to pimp your shiny apps !" 😂
