### ISSUE TITLE
capture user emails

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#15]
**Short term:**
Would be good to ask for and capture user email addresses, perhaps on the download report page (as opposed to a login front page required for use of the site); getting user information would be helpful for notifying of future releases, etc.

**Long term:**
Would be good to have login credentials for users that would allow them to store previous lookups, previous reports (PDFs). Inspired by gene-clime.org (Broad Institute resource)

**Comment by johnbradley** [comment]
PR #17 Added UI that prompts a user for name and email address before downloading pdfs.
The users name and email address is now saved into a RDS file under `data/users`.
This is a good step forward but has some drawbacks: https://github.com/hirscheylab/ddh/pull/17#issuecomment-568752237

Typically we use a SQL(relational) database to store this type of data. The R [DBI module](https://dbi.r-dbi.org/) allows you to write code that can communicate with many different database backends. There is a [dbWriteTable](https://dbi.r-dbi.org/reference/dbwritetable) function that saves a data frame to the DB under a table name. 

Adding a relational database to the deployment such as PostgreSQL is pretty straight forward. Something to consider about adding a relational database to your app is how you will continue to develop. If you are comfortable running a relational database such as PostgreSQL locally then this is trivial. If not you may want to consider using SQLite for local development. SQLite doesn't have any complicated requirements and can save the database to a file or just keep it in memory which is what the example code above does.

**Comment by johnbradley** [comment]
PR #44 moved the per user Rds files into a separate volume and directory from the generated data.
Our current deployment supports shared writable volumes so saving data to files on disk will not be 
a problem for scaling up. I think we can proceed for now and accomplish the __Short term__ goal above writing user email data to files on disk as we are doing now.

The only remaining thing to consider is the format we save user data in. Right now we are saving the user email data as Rds. Saving the data as csv would be more accessible. @hirscheylab Do you remember if there was a specific reason for using Rds? Do you have any reservations on switching to csv?

**Comment by matthewhirschey** [comment]
No reservations about .csv, Rds was just for a simple test case. 
Go ahead and write_csv()
