### ISSUE TITLE
enrichr_loop column conversion error

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#22]
I encountered an error running `generate_depmap_pathways.R` with the `19Q4` data.

When running the [enrichr_loop](https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/generate_depmap_pathways.R#L16-L30) for gene `VPS45` with the `19Q4` data the following error occurs:
```
Error: Column `Term` can't be converted from character to integer
```
This error is raised from here:
https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/generate_depmap_pathways.R#L23

You can reproduce this error by running the following:
```
gene_list <- c("SPANXN5","ART1","IFNK","DEFB124","MT1B","CA5A","PPIAL4G","G6PC2","LYPD2","SSX3","RFPL3","FMO2","OR8S1","PMPCB","IL26","XAGE3","LRRC18")
focused_lib <- c("PPI_Hub_Proteins", "Rare_Diseases_AutoRIF_ARCHS4_Predictions")
enrichr_loop(gene_list, focused_lib) 
``` 

The problem seems to be related to `PPI_Hub_Proteins` response containing a single row with a `Term` column that contains an integer value of `231403`. All the other libraries contain a character value for Term. So when we bind these data frames together the error occurs.

I was able to work around this issue by casting the Term field to character before running `bind_rows`.

**Comment by matthewhirschey** [comment]
@johnbradley 
Good catch! I got the same error working with VPS45, but didn't track down the problem. 
Thanks!!!
