### ISSUE TITLE
Makefile/openshift changes missed in 19Q4 upgrade

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#23]
PR #17 updated to use the `19Q4` data. A few places still need to be updated from `19Q3` to `19Q4`.
The Makefile still contains `19Q3` files such as:
https://github.com/hirscheylab/ddh/blob/9182d841082c3ac7e510f106245730791f5fa6f4/Makefile#L37

The openshift file list also needs to be updated:
https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/openshift/file-list.json#L4

**Comment by johnbradley** [comment]
I also noticed there are some `19Q3` entries in the `code/eda` directory:
https://github.com/hirscheylab/ddh/blob/aeab2187e864d516f598858dbf57960ee04930ac/code/eda/depmap_explore.Rmd#L7

I am not sure if they need to be updated as well.

**Comment by matthewhirschey** [comment]
@johnbradley : 
These are EDA, so they don't need to be updated for the app. 
I will slowly update the EDA code to load the same data generated in the generate*.R scripts, rather than generating it de novo.
