### ISSUE TITLE
within OpenShift app.R can't find the code directory

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#29]
Within openshift the current release is failing with:
```
Warning in file(filename, "r", encoding = encoding) :
cannot open file '/srv/code/current_release.R': No such file or directory
```

The shiny Dockerfile copies the contents of the `code` directory to a directory named `shiny-server`.
https://github.com/hirscheylab/ddh/blob/97422a539ab464838ce3b2715823a32b178bb201/Dockerfile.shiny#L40-L42

The app.R script tries to import files within code based on the `.here` file.
https://github.com/hirscheylab/ddh/blob/97422a539ab464838ce3b2715823a32b178bb201/code/app.R#L20

**Comment by johnbradley** [comment]
@dleehr Any thoughts on this issue?

**Comment by dleehr** [comment]
I started working on the fix for that in https://github.com/Duke-GCB/ddh/tree/build-fixes before the break, but didn't get to the point of pull-requesting it yet.
