### ISSUE TITLE
"Download Report" tab should prompt user to enter a gene 

### ISSUE THREAD

**Issue by dleehr** [matthewhirschey/ddh.org#32]
The other tabs display "Enter a gene symbol to ..." when the user has not yet entered a gene symbol. The **Download Report** tab does not, and will allow the user to download a `report.txt` file containing an error message.

**Comment by dleehr** [comment]
<img width="946" alt="empty gene sybmol download report" src="https://user-images.githubusercontent.com/2752599/72093615-b4784500-32e2-11ea-9874-4f4f9bdd7108.png">

**Comment by matthewhirschey** [comment]
Need to wrap this page in a conditional panel

**Comment by matthewhirschey** [comment]
fixed with last commit
