### ISSUE TITLE
Memory and startup time optimizations

### ISSUE THREAD

**Issue by dleehr** [matthewhirschey/ddh.org#34]
Currently the app.R startup takes a minute or two, and loads all of the data files into memory. This uses 4-5GB at rest. 

More details to come

**Comment by dleehr** [comment]
Looked into this today.

- Tried to use [lazyLoad](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/lazyLoad), but that's for R packages and internal apparently?
- Tried to use mmap to memory-map the data, but that didn't work with a data frame, seems to expect fixed size data structures
- Might be able to use mmap.csv, but we'd have to move data to CSV

From a practical/optimization standpoint, I've been looking at the `achilles_cor` object, since that's the largest file (over 2GB). It's a correlation matrix at 18000x18000

- Tried to write it to SQL (SQLite and Postgres) but both drivers complain about too many columns. PostgreSQL was limited to 1600 and SQLite did not advertise its limit

With SQL indexing, it might be performant to stretch the correlation matrix out into a long 3-column table. the corrr package has "stretch" that does just this.

I stretched this out to 336 million rows and am attempting to write it to a Postgres table:. It's been running for a while locally, but should work

```
library(corrr)
library(DBI)
library(RPostgres)
load("./ddh-data/data/19Q3_achilles_cor.RData")
achilles_cor <- stretch(achilles_cor)
pcon <- dbConnect(RPostgres::Postgres())
dbWriteTable(pcon, name = "achilles_cor", value = achilles_cor)
```

In the meantime, I noticed this object is only used when writing out the report, so that's worth considering. To see how much memory/time we'd save on startup I'm going to:

1. Edit app.R to not load this file
2. See what memory usage is
3. Confirm `achilles_cor` is only used when writing a report
4. Write the long the database table and index it. (how big is this?)
6. update the code to query the database
7. Compare performance/memory usage

**Comment by dleehr** [comment]
Like I say, I'll first see how much this will help (moving the correlation matrix out of an RData file and into a queryable database). At that point I may need some guidance rewriting this loop to query the database instead of a local dataframe.

https://github.com/hirscheylab/ddh/blob/e346df35b25292dbc29cc222092539e8229470a7/code/app.R#L175-L201

**Comment by matthewhirschey** [comment]
NB: achilles_cor is used to generate the graph, as well as the graph_report

**Comment by matthewhirschey** [comment]
Just realized: the information that achilles_cor provides for those two functions are could also be taken from the master_tables. Master table is a short version (cut at the threshold) of each gene with each other gene, but since the graphs only use the top 10 genes, these could easily be extracted. 

Let me think about this, but perhaps the easiest way is to not load the file at all...

**Comment by matthewhirschey** [comment]
💪Re-wrote make_graph() and make_graph_report() to pull data from master_top/bottom_table, in place of pulling data from achilles_cor. This update circumvents the need to load achilles_cor. These data are still required in the generate_*.R scripts, but not for the app. I can PR these changes along with the changes that @johnbradley suggested from my last PR.

**Comment by dleehr** [comment]
Cool. I'm pulling these changes down now and checking the memory usage. That should make a big difference if we don't even need to load  achilles\_cor in the first place 👍

**Comment by dleehr** [comment]
After merging #38 and re-deployment, memory usage is down to 1.4GB. Big improvement, and I'm comfortable scaling up to 2 or 3 instances now if needed.
