### ISSUE TITLE
cannot search for C#orf###

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#40]
C open reading frames (Corfs) have lower case characters in their official gene symbol. str_to_upper(input$gene_symbol) breaks this. 
I'll add an if_else to detect for this rare case.

**Comment by matthewhirschey** [comment]
Cannot search for a gene that's in the db
![Screenshot 2020-01-14 11 18 21](https://user-images.githubusercontent.com/36932093/72363731-4d340980-36c3-11ea-9801-b495033a71ad.png)
Should be C8orf82

**Comment by matthewhirschey** [comment]
@dleehr and @johnbradley 
I deleted the develop branch, as you suggested after the last merge. I also started a new branch for some validation work, EDA, etc. 

Q: What is the best way for me to fix some of these minor issues (as above)? New branch for them? Push to master?

**Comment by johnbradley** [comment]
> Q: What is the best way for me to fix some of these minor issues (as above)? New branch for them? Push to master?

@hirscheylab I prefer to always create a new branch and a PR for that branch. That way you can tie this issue to a PR. Then if the issue re-surfaces we can easily track down where the problem might reside.
