### ISSUE TITLE
Need better feedback for gene not found in db

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#41]
The only feedback if a gene is not found is to "type the official gene symbol". But in some cases, the gene is legitimately not in the DB (because it was not there in the first place, or because I filtered it out). Should be more informative if this is the case. Currently throws an error. 

![Screenshot 2020-01-14 11 18 52](https://user-images.githubusercontent.com/36932093/72363890-9be1a380-36c3-11ea-8bbc-dfc99895be8f.png)

ADIPOQ is a gene that has a gene symbol (in gene_summary), but I filtered it out because it was below my stated threshold.

**Comment by matthewhirschey** [comment]
Thinking about a strategy to approach this, hoping to get your thoughts @johnbradley, since you've just thought a lot about the gene_symbols, etc.

For almost every case (except ~10 genes) the input$gene_symbol == gene_summary$approved_symbol. 

But the number of genes in gene_summary$approved_symbol will be significantly greater than the number of genes in the correlation data (or in this case, the gene_symbols in any of our nested tables). 

For simplicity (and performance), I might create an .RData object that is a vector of gene_names that are within the dataset (would add this to the generate_depmap_data.R script), and load it as usual.

Then, I can add (and additional) conditionalPanel to each UI element, that checks to see if the gene symbol is in the dataset (in the vector representing the dataset); if not, then display a message; if so, then display the data.

This might still display an error if one of the genes with mismatching gene_names/gene_symbols is queried, but this is a rare use case. And instead of using this issue to solve that problem, I think we'll need to extend your recent solution in issue #49 to solve all mismatch problems. 

Thoughts?

**Comment by johnbradley** [comment]
One option to fix this issue is to add `validate` to `renderDataTable`/etc. 
Using `validate` you can specify a message to display instead of the table/plot when a condition is met.

If you change this code:
https://github.com/hirscheylab/ddh/blob/9db9a648cfecc099c7ef2fe9a5595429ba1782b0/code/app.R#L483-L486

To specify that the gene symbol must be in master_top_table$fav_gene:
```
  output$dep_top <- DT::renderDataTable({
    validate(
      need(input$gene_symbol %in% master_top_table$fav_gene, "No data found for this gene."))
    DT::datatable(
      make_top_table(data()), 
      options = list(pageLength = 25))
  })
```

It will display the message like so for ADIPOQ:
<img width="433" alt="Screen Shot 2020-01-27 at 11 17 50 AM" src="https://user-images.githubusercontent.com/1024463/73192217-b6217580-40f6-11ea-8aac-26064b82e78a.png">

Validate documentation: https://shiny.rstudio.com/reference/shiny/0.14/validate.html

**Comment by matthewhirschey** [comment]
A+! 
Will create a new branch to add several `validate()` lines to each of the outputs. 
Good find!

**Comment by matthewhirschey** [comment]
Too many genes are coming up with "data not found"
When I run the master branch locally, this is not an issue.
e.g. TP53BP1

**Comment by matthewhirschey** [comment]
Looking more closely, looks like the issue might be that as soon as a gene for 'data not found' is returned, then all subsequent searches come back as 'data not found'. Including TP53. 

To recreate the bug. 
1. From a fresh page, search for TP53; look for similar genes (plenty found).
2. Go back home, and search for ADIPOQ; look for similar genes (not found).
3. Go back home, and search for TP53; look for similar genes (not found).

*I can recreate the same behavior on ddh.org AND on my local shiny app*
