### ISSUE TITLE
Improve concurrent user handling / scalability

### ISSUE THREAD

**Issue by dleehr** [matthewhirschey/ddh.org#55]
After deploying ddh to openshift, we find that the shiny server process ([Shiny Server Open Source](https://rstudio.com/products/shiny/shiny-server/) can only respond to a single user action at a time. A consequence here is that when a single instance is busy doing work (e.g. spending 5-10 seconds building a PDF for download), that instance will not respond to any other requests (including displaying the main page) until the action completes. We discussed on the call today, and it's an important concern before promoting the site. See also https://github.com/hirscheylab/ddh/pull/45#issuecomment-575649905

To handle traffic from more than tens or hundreds of active users, we should run more than 1 instance. So while 1 is probably too little, I think 100 would be overkill. I suspect 5-10 would be good fit. Some tasks below that I'll assign 😄 

- [x] We need to have an idea how many users to expect. Do we expect 100 users all attempting to download 50 reports each for 4 hours at a time? Do we expect 1000 users to load the site, 100 to browse data, and 50 to download reports over a 6 hour period? @hirscheylab 
- [x] We need to understand how the application behaves when it is at or over capacity. @johnbradley 
- [x] Shiny-server open source is not stateless and user actions depend on sessions. So any load balancing configuration that distributes to multiple replicas would need to keep sessions sticky to replicas. In our current configuration with 2 replicas, we need to confirm this is working correctly (It seems to be) @dleehr 

Other notes:

- Thanks to some optimizations (#34, #52), each instance uses 1GB RAM (down from 5GB). Our project quota is 4GB for requests, so we could run up to 4 instances. 4 or 5 is probably a good start to handle 20-50 users. There is increased cost to using more sustained resources, so it's important to get the balance right.
- Openshift does support [horizontal pod autoscaling](https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html#hpa-autoscaling). This automatically launches or terminates pods based on CPU or memory utilization. This only works if those metrics are a proxy for server load. With shiny server, I haven't seen these values fluctuate when using the app. It's either busy or not busy. Unless we can rewrite the app to use more memory or CPU when it's busy (and less when it's not), I don't think this helps.
- I suggested moving some of the longer-running actions (like PDF download and plot generation) to dedicated URL routes/paths so that they do not block simple browsing. We could run fewer instances, but users who want to get reports may have to wait. I think that's a reasonable tradeoff, and we do this in [datadelivery](https://github.com/Duke-GCB/gcb-ansible-roles/blob/837bec8a9b8f4801025613b84d18c427e9b263f2/d4s2_webapp/files/nginx.conf#L31-L46) using nginx for long-running downloads. That application is stateless and has clear URL paths for different services, and those don't hold true for this one. I have some other ideas along this line, but they require some more significant refactoring/rearchitecting.

**Comment by dleehr** [comment]
From today's notes:

> 3 things that take time - building plots, building graphs, generate report

**Comment by johnbradley** [comment]
Another option to run a shiny app is https://www.shinyproxy.io/.

**Comment by johnbradley** [comment]
Here is a blog post about running a background process for long running tasks: https://www.r-bloggers.com/long-running-tasks-with-shiny-challenges-and-solutions/

**Comment by johnbradley** [comment]
Testing the app with two users I only see noticeable pauses when one is using the __Report Generator__. Once the report is finished generating the other user's session continues as normal. It looks like the two users were only making use of one pod in the cluster. The other pod seems to be idle.

**Comment by dleehr** [comment]
Some notes from trying [shinyproxy](https://www.shinyproxy.io)

- It's conceptually a lot like JupyterHub - it's a proxying web app that handles user authentication and launching containers on different backends.
- To use it, you write a a config file [application.yml](https://www.shinyproxy.io/configuration/) and run `shinyproxy.jar`. The shinyproxy.jar itself can run inside a container
- The application.yml specifies if/how to authenticate users, what container backend to use (docker, k8s, swarm), which docker images to run, and what resources they need (volumes, memory, cpu, etc), 
- If authentication is disabled, visiting the proxy just lists all the registered docker images. Clicking one launches a container for it. If authentication is configured, you must log in first.
- Visiting in different browsers (different sessions) will result in multiple containers being launched.
- Containers are not pre-loaded. It takes about 20 seconds for ddh to be up and running. Again, a lot like our JupyterHub server.
- it adds a navigation bar with a logo and logout button to the app

I just ran this under local java talking to Docker on my mac. It worked, but isn't perfect for a public-facing web site. I did confirm though that with 2 separate browsers there are 2 containers running and both can actively browse and download reports simultaneously. the container CPU usage spikes to 100% while generating the report, then drops back off.

**Comment by dleehr** [comment]
Other notes of significance from today:

- @johnbradley and I tried to stress test the application simultaneously, and found that only 1 of the 2 pods ever logged any traffic (the application logs when reports are generated and a few other actions). We found that one of us downloading a report always blocked the other's activity, even though there should have been a second pod to take over.
- The Kubernetes service supports a sessionAffinity parameter that can be set to `clientIP` for sticky sessions. But this didn't make any difference if the second pod was always idle.
- The third "async" approach in https://www.r-bloggers.com/long-running-tasks-with-shiny-challenges-and-solutions/ seems like it would work well for the long-running tasks.

**Comment by johnbradley** [comment]
@dleehr Would you like me to look into using `The third "async" approach` for generating the pdf report?

**Comment by dleehr** [comment]
I think it would be good to do regardless. I may take a look today but if you have time, go ahead

**Comment by dleehr** [comment]
Some updates

1. There's a server config parameter for how many concurrent connections a server can accept, from https://docs.rstudio.com/shiny-server/#simple-scheduler:

> The Simple Scheduler is the only scheduler available in the Open Source edition of Shiny Server. It associates a single R process with a single Shiny application. This scheduler accepts a single parameter which specifies the maximum number of concurrent sessions. Once this number is reached, users attempting to create a new session on this application will receive a 503 error page.

2. I'm trying to adapt the example for async download handlers at https://stackoverflow.com/questions/53478197/r-shiny-async-downloadhandler and https://community.rstudio.com/t/r-shiny-async-downloadhandler/18937 but not having much luck. The download never starts and the app doesn't respond to other things.

**Comment by johnbradley** [comment]
I also tried looking at async download handlers. 
When using `future` the first step is to pick a plan: `plan(<PLAN_NAME>)`.
I tried using the `multiprocess` plan since it sounded like it would be more performant than `multisession` based on [Multicore Futures documentation](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html).
> Forking an R process can be faster than working with a separate R session running in the background. One reason is that the overhead of exporting large globals to the background session can be greater than when forking, and therefore shared memory, is used.

It sounds like `multisession` must serialize and deserialize data used in the future function. Since we have some large data frames this could be why a future hangs.

However when I tried to use `multiprocess` from within Rstudio which prints a warning that it is can only use `multisession`.
```
> library(future)
> plan(multiprocess)
Warning message:
[ONE-TIME WARNING] Forked processing ('multicore') is disabled in future (>= 1.13.0) when running R from RStudio, because it is considered unstable. Because of this, plan("multicore") will fall back to plan("sequential"), and plan("multiprocess") will fall back to plan("multisession") - not plan("multicore") as in the past. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?future::supportsMulticore
```
I found that this warning did not occur if the app was run from the command line.
Having an app work differently in RStudio vs command line is kind of frustrating.

There is also some [Caveats and limitations documentation](https://cran.r-project.org/web/packages/promises/vignettes/futures.html) for using `future`.

`future` does `automatic detection` to determine what variables need to be passed to the background process. Notes on globals:
> it’s possible for both false positives (data copied that doesn’t need to be) and false negatives (data not available when it’s needed) 

It doesn't seem to correctly inspect into our R markdown documents properly.
For example I hit a `false negative` related to `current_release.R` and had to add:
```
source(here::here("code", "current_release.R"))
```
inside a future function even though it was already loaded.
Fixing these bugs are quite challenging because you have to wait for the future to finish to get an error message back which can take quite a while.


Perhaps we should look at breaking out the PDF creation into a separate Rscript.

**Comment by johnbradley** [comment]
Also there isn't a simple method to cancel/interrupt/terminate a `future`. I found an issue with some `multiprocess` attempts to do so: https://github.com/HenrikBengtsson/future/issues/93

**Comment by johnbradley** [comment]
I looked at two options to prevent blocking other users while generating a pdf.

## Option: Use future (async download handlers)

This option uses a future to create the pdf in the background.
Testing this with our report creation code I found that `multisession` is just really slow compared to `multicore`. `multicore` forks the process and immediately has all memory loaded whereas `multisession` must pass all the data. RStudio only supports `multisession`.
 
I have a branch with changes that generate the PDF in the background and shiny remains responsive for other users:
https://github.com/hirscheylab/ddh/compare/master...Duke-GCB:55-multiprocess-future-pdf-creation
This branch needs some work on the progress bar.

If run from within RStudio this branch takes ~2 minutes to create a pdf. If run from the command line (which uses `multicore/multiprocess`) it takes ~ 16 seconds to create the same pdf.

To run shiny from the command line in the `code` directory run:
```
R -e "shiny::runApp('.')"
```

There is also a `future` option where we could choose to not pass anything to the future and re-read the data there. This would be faster in `multisession` but slower in  `multicore`.

Note: The `multiprocess` plan tries to use `multicore` but will fall back to `multisession`.

## Option: Separate R script to generate a pdf
The idea is to separate out parts of app.R that generate the report.
Then wrap this up in some kind of app that spawns R code on demand.
In testing this adds about 15 seconds to how long creating a report takes.

In particular the following lines take 13 seconds.
https://github.com/hirscheylab/ddh/blob/3eaa0f955abb3fc2552b92356eccbbcf67c992d6/code/app.R#L36-L40

This would require some other wrapper code.

**Comment by matthewhirschey** [comment]
A few comments on current users and load. 

- This week we had 36 users (all from direct, none from search) for 82 sessions
- 28 of the users were new
- Average session length was ~7 min
- The only page we have is the home page (everything else is a frame in the page), so the bounce rate (those that leave after viewing one page) is high. 
- I cannot track who makes reports, and who just browses from these data. I could try to put a tracking URL into that frame to get more granular information, but that was part of the reason to get the email addresses...to see who gets that far and to be able to contact them. If we carve out the report_generator into it's own process/script, we could certainly do this

**So my best estimate:**
We will have up to 50 concurrent users after "announcing" the resource (preprint, publication, twitter, etc.) -- high estimate, but unlikely higher
These users will spend no more than 10 minutes on the site
I would expect that the download report function is currently low, and would probably remain quite low, compared to total users (maybe 1:10?)


<img width="691" alt="Screenshot 2020-02-08 09 10 35" src="https://user-images.githubusercontent.com/36932093/74086664-01bb1400-4a53-11ea-9a4b-502f3a474307.png">


<img width="1145" alt="Screenshot 2020-02-08 09 09 26" src="https://user-images.githubusercontent.com/36932093/74086667-097ab880-4a53-11ea-9466-52b117d299c3.png">


<img width="1144" alt="Screenshot 2020-02-08 09 09 09" src="https://user-images.githubusercontent.com/36932093/74086675-15667a80-4a53-11ea-8133-99eb7f62ea6e.png">

**Comment by matthewhirschey** [comment]
I'm following the conversations above about possible solutions. 
One quick question @dleehr @johnbradley :
Is there an 'easy' fix if we purchased a license from RStudio of their products (Rstudio connect or the like)? This isn't out of the question, but wanted to see if the hoop-jumping above is because we're trying to find a free solution.

**Comment by johnbradley** [comment]
@hirscheylab I think we can use the `multiprocess/multicore` plan with `future` in our deployed server and avoid the behavior where all users are stalled during PDF creation. To avoid the problems with running inside RStudio I can just skip using `future` while developing within RStudio. After this change I hope we will be close to supporting 50 concurrent users.

**Comment by dleehr** [comment]
John's research above proved that there's a [simple fix](https://github.com/hirscheylab/ddh/compare/master...Duke-GCB:55-multiprocess-future-pdf-creation) for not tying up the server while generating a download PDF. And we can edit the shiny-server config to increase the number of concurrent users, so I think that's a good way to get to this milestone.

The only caveat with this simple fix is that it doesn't work as well within RStudio. (_Though I'm not clear if it breaks or falls back to a slower version. If the latter, I'm not convinced we need to complicate things any further_). It'll work great on our openshift cloud deployment, but we may want to tweak the code to skip using `future` when running under RStudio (your local development).

> Is there an 'easy' fix if we purchased a license from RStudio of their products (Rstudio connect or the like)? 

A licensed product may be a fix but I don't think it's easy. It looks like [Shiny Server Pro](https://rstudio.com/products/shiny-server-pro/) would be the best fit from their commercial offerings, but they don't seem to publicize that much. I don't think it's a drop-in replacement. We don't know if it can run under Openshift easily, and the licensing would certainly limit how many pods we could run. It's a tradeoff I wouldn't recommend digging into right now.

> This isn't out of the question, but wanted to see if the hoop-jumping above is because we're trying to find a free solution.

That's a fair question. I'm not on a crusade for a free solution 💸  There are some benefits to the commercial shiny server pro, but I think most of the hoop jumping has been John and I learning how to apply our experience to shiny server. I believe we can reach the stated goals with a few simple configuration changes. After that, sure  it makes sense to review the technology/architecture choices looking towards what you want to do next.

**Comment by matthewhirschey** [comment]
Wow. Deep dive, but sounds like you have found a good solution. I was playing with `future` this weekend, and I think that in Rstudio `multiprocess` defaults back to sequential rather than parallel in Rstudio because of some instability. So the code you write won't break in a local deployment of Rstudio, but it won't be able to off-load the parallel task to another core, so won't get the benefit (as I understand) of the parallel processing to off-load PDF tasks. 

I agree with @dleehr that the solution @johnbradley found should be the simplest mechanism to solve this issue!

**Comment by johnbradley** [comment]
I have deployed the changes to create PDFs in the background to the website.

The deployment initially failed due to an error about missing the new R modules (future and promises). The `base-shiny` docker image was not automatically rebuilt.
I went into openshift under Builds -> base-shiny and clicked the "Start Build". This updated everything and redeployed the app successfully.

**Comment by dleehr** [comment]
I was about to update the shiny-server.conf to set the max connections to 50, but the default is already 100:

https://github.com/rstudio/shiny-server/blob/5cf1d8d03611004d8d4bc1d4ebb7bbccd46df5e5/lib/router/config-router-util.js#L51-L58

So I don't think we need to make any changes there.

**Comment by dleehr** [comment]
Also, while accessing the site from 2 browsers (Safari and Chrome), I can confirm that both pods are receiving traffic. Each browser was focused on a different gene and this worked as expected. So I think everything in this issue is wrapped up. We can run more pods that will handle more traffic 👍

**Comment by johnbradley** [comment]
Discussed and agreed this is resolved.
