### ISSUE TITLE
ddh.org -> www.ddh.org

### ISSUE THREAD

**Issue by matthewhirschey** [matthewhirschey/ddh.org#66]
Root ddh.org does not resolve website. 
Need to redirect to www (where the ssl lives)

**Comment by johnbradley** [comment]
This was fixed for http://datadrivenhypothesis.org but is still a problem for https://datadrivenhypothesis.org 
![Screen Shot 2020-02-27 at 2 53 20 PM](https://user-images.githubusercontent.com/1024463/75481369-f2075f00-5970-11ea-902f-8ff9fd307942.png)

**Comment by johnbradley** [comment]
I setup an additional route in OpenShift that has fixed the above error. I still need to document this additional route in the openshift config.

**Comment by johnbradley** [comment]
The additional route has been added/documented in the role that deploys DDH: https://github.com/Duke-GCB/gcb-ansible-roles/pull/83
