### ISSUE TITLE
Allow users to view data for a pathway

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#68]
Currently the website only allows users to view data for one gene.
During our last meeting @hirscheylab mentioned that supporting a pathway oriented view of the data would be a meaningful expansion to the value this website provides.
For this improvement we need to consider how to organize the content into separate pages.

**Comment by johnbradley** [comment]
# Organizing Pages
Below are two approaches I have come across for supporting a larger shiny app with more pages.

## Option1: Shiny server directory of Applications
The shiny server supports [hosting multiple apps each within a separate directory](https://docs.rstudio.com/shiny-server/#host-a-directory-of-applications). 
Instead of:
```
code/app.R
```
We would have something like:
```
code/gene/app.R
code/pathway/app.R
```
These two app.R files would serve `datadrivenhypothesis.org/gene/` and `datadrivenhypothesis.org/pathway/` respectively.

With this option a user is expected to create an index.html file in the top directory to allow the user to navigate to the various apps. So we would also need to add:
```
code/index.html
```

The only downsides I have come across to this are 
- RStudio runs apps one at a time so debugging hyperlinks that navigate between apps will be more difficult. There is no native mac support for shiny-server so it requires docker to test multiple apps cohesively.
- This might use more memory than the more complicated options below due to apps not sharing data.

It could provide a URL that looks similar to: `datadrivenhypothesis.org/gene/?symbol=BRCA1` for viewing the BRCA1 gene.

## Option2: Use shiny.router
There is R library that lets you support multiple "pages" via one app named [shiny.router](https://github.com/Appsilon/shiny.router)
Each page ends up with a separate `ui` and `server` type function.
A good walkthrough is available here:
https://appsilon.com/shiny-router-a-simple-routing-package-for-shiny/

The downsides from this are:

- It makes use of unexpected URLs. For example we might end up with something like `datadrivenhypothesis.org/?symbol=BRCA1#!/gene` for the URL for viewing the BRCA1 gene. In the code this url is referred to as `/gene` which I found confusing.
- The code will require more effort to keep it well organized since everything is handled within a single app.R file.

The only positive I can see is the "pages" should be able to share data between them.

**Comment by matthewhirschey** [comment]
## Option3: More conditional pages
We could still use one app.R file, but instead dictate the downstream behavior based on what is input into the search box.

Benefits are: 
- It makes one app to maintain rather than two
- It would allow for easier linking between genes and pathways

Drawbacks are: 
- More complicated conditional code
- Could make longer load up times and/or memory allocation, as additional data files would likely need to be loaded that might never be used in a use case

**Comment by matthewhirschey** [comment]
Made a `pathways` branch (https://github.com/hirscheylab/ddh/tree/pathways) to test option #2 above

**Comment by johnbradley** [comment]
In testing out `Option2: Use shiny.router` I have hit a problem where the app is unresponsive after a user clicks the browser back button multiple times. I think it is related to this issue: https://github.com/Appsilon/shiny.router/issues/67

I also noticed that `shiny.router` seems to be using an iframe which was unexpected. I haven't used iframes in a while, but when I did I found them difficult to get right.

**Comment by matthewhirschey** [comment]
@johnbradley:
As I build out the pathways UI and reports, it might be helpful to have a content page type specifically for the custom gene list. We currently have 

content=gene&symbol=BRCA1
content=pathway$go=123456
content=pathway&custom_gene_list=BRCA1,BRCA2

Can you make the custom_gene_list a content type? 
This way it could be programmatically accessible for report generation.

**Comment by johnbradley** [comment]
> Can you make the custom_gene_list a content type?

Sure. I will create a PR @matthewhirschey

**Comment by matthewhirschey** [comment]
PR #87 adds this feature
