### ISSUE TITLE
consolidate to a single data generation method

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#73]
We currently have to files that both specify the data generation process:

`code/quarterly_release.R` is currently used in the development and testing new releases

https://github.com/matthewhirschey/ddh/blob/16b744b7e1089a74a783006fbc3c10ba1c7198e3/code/quarterly_release.R#L4-L9

The `Makefile` is used to generate data for the website. 

https://github.com/matthewhirschey/ddh/blob/16b744b7e1089a74a783006fbc3c10ba1c7198e3/Makefile#L48-L58

I would like for us to consider dropping one of these methods.

Discussion: https://github.com/matthewhirschey/ddh/pull/72#discussion_r392593820

**Comment by matthewhirschey** [comment]
Issue fixed by generate_data.R script
