### ISSUE TITLE
Remaining issues to hosting application

### ISSUE THREAD

**Issue by dleehr** [matthewhirschey/ddh.org#8]
I pulled the latest changes to the repo and downloaded the data from the dds project. I was able to get the app launched locally under docker, and have identified the following issues:

- [x] The `expression_join` object is missing - I don't see a script that generates it.
- [x] Increase memory limits in openshift project. Our cloud project has a default limit of 2GB. The app requires at least 2.6 GB of memory to run, so I requested an increase to 8GB quota. We may be able to optimize this but I wanted to get it up and running first.
- [x] app.R loads files without the versioning prefix (e.g. `achilles.RData`) but the files we have include the prefix (e.g. `19Q3_achilles.Rdata`). I addressed this with symlinks for now but it relates to #6 
- [x] The `includeMarkdown(here::here("code", "methods.md"))` fails under openshift because it's looking in the data directory for code
- [x] `make_enrichment_table` on line 93 fails with Error in .f: object 'enrichr' not found
- [x] Report download fails, but the error is `'expression_join' not found`

I'll create separate issues for showing you how to login to openshift, reconfiguring the auto build from GitHub, and configuring the CNAME. But we're close!

**Comment by matthewhirschey** [comment]
Added line of code to save expression_join in generate_depmap_data.R, which should also fix the report download failure; updated app.R to load the version prefix;

**Comment by dleehr** [comment]
I created a ticket to raise the memory request/limits and OIT sorted that out this morning. Details below:

In the deployment, we were setting 1G memory `limits` that was exceeded and openshift was terminating the container as it loaded the data and needed about 2.6GB:

https://github.com/hirscheylab/ddh/blob/93c3a1f8cb22ccff240a6ec24797fbd83f58ca96/openshift/application.yaml#L118-L120

I tried to fix this by editing the YAML and setting the memory `requests`(not `limits`) higher. Openshift complained that this was over our project quota, so I submitted a servicenow ticket to raise `requests` to 8GB.

OIT contacted me this morning to clarify. `requests` is the floor (how much memory you need to guarantee) and `limits` is the ceiling (how much your container is allowed to use if available). The default `limits` are set to 7GB, so if we hadn't specified 1GB, the app should have started without issue because 2.6 is within the limit of 7GB.

To better address the use case, they raised the `requests` (floor) quota to 4GB, allowing us to demand about 3GB of memory and stay under 7GB.

**Comment by dleehr** [comment]
#12 fixes a few of the items. Here are the current items - you can see at http://depmap-shiny.apps.cloud.duke.edu:

- [ ] **Cell Dependencies -> Plots/Table** fails with log: `Warning: Error in .f: object 'cell_line' not found`
- [ ] **Similar/Dissimilar-> Pathways** fails with log: `Warning: Error in .f: object 'enrichr' not found` (This was noted above but I didn't have the steps)
- [ ] **Similar/Dissimilar -> Genes** Displays single letter values for Gene, name, and R^2. Not sure what's the cause here.
- [ ] **Graph** fails with log: `Warning: Error in %in%: object 'fav_gene' not found`
- [ ] **Methods** displays the lamp post image but none of the other graphics
- [ ] **Download Report -> Download report** downloads a `report.txt` file and fails with log: `Warning: Error in .f: object 'cell_line' not found`

@hirscheylab would you be open to working with a branch/pull-request/review process when addressing some of these? We're probably about ready for another meeting 😄

**Comment by dleehr** [comment]
Items for @dleehr:

- [ ] Split Dockerfile to avoid re-installing all base dependencies every time
- [ ] Update Dockerfile build to place code at /srv/code (removing shiny-server examples and fixing markdown due to flattening)
- [ ] Add methods knitting to Makefile

**Comment by matthewhirschey** [comment]
@dleehr : do we also have a problem with the paths to find the data for  Similar/Dissimilar-> Pathways & Genes? As well as Plots/Table? The errors look like the data isn't found at all. But is working on my version. Recall that we used here::here("data", "file.RData") for these, but you set up a step in the make file to copy data/*. Just curious if it's a path issue here too.
